import { RouteInfo } from "./vertical-menu.metadata";
import { environment } from "../../../environments/environment";

let routeinuse = [
  {
    path: "/tables/home",
    title: "Home",
    icon: "icon-home",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    isImportant: false,
    submenu: [],
  },
  {
    path: "",
    title: "Customer",
    icon: "icon-users",
    class: "has-sub",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    isImportant: false,
    submenu: [
      {
        path: "/tables/mainTable",
        title: "Customer List",
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        isImportant: false,
        submenu: [],
      },
      {
        path: "/forms/createNewCustomer",
        title: "New Customer",
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        isImportant: true,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Loan",
    icon: "icon-calculator",
    class: "has-sub",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    isImportant: false,
    submenu: [
      {
        path: "/tables/loanTable",
        title: "Loan List",
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        isImportant: false,
        submenu: [],
      },
      {
        path: "/forms/createNewLoan",
        title: "New Loan (Normal)",
        queryParams: {
          isUnlimited: false,
        },
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        isImportant: true,
        submenu: [],
      },
      {
        path: "/forms/createNewLoan",
        title: "New Loan (Unlimited)",
        queryParams: {
          isUnlimited: true,
        },
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        isImportant: true,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Agent",
    icon: "icon-users",
    class: "has-sub",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    isImportant: true,
    submenu: [
      {
        path: "/tables/userTable",
        title: "Agent List",
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        isImportant: true,
        submenu: [],
      },
      {
        path: "/forms/createNewUser",
        title: "New Agent",
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        isImportant: true,
        submenu: [],
      },
    ],
  },
  {
    path: "/pages/login",
    title: "Logout",
    icon: "icon-logout",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    isImportant: false,
    submenu: [],
  },
];

console.log("is production", environment.production);
if (!environment.production) {
  routeinuse = routeinuse.concat([
    {
      path: "",
      title: "Tables",
      icon: "ft-grid",
      class: "has-sub",
      badge: "",
      badgeClass: "",
      isExternalLink: false,
      isImportant: false,
      submenu: [
        {
          path: "/tables/basic",
          title: "Basic",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/tables/extended",
          title: "Extended",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/tables/tables",
          title: "Angular",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
      ],
    },
    {
      path: "/datatables",
      title: "Data Tables",
      icon: "ft-layout",
      class: "",
      badge: "",
      badgeClass: "",
      isExternalLink: false,
      isImportant: false,
      submenu: [],
    },

    {
      path: "",
      title: "uikit",
      icon: "ft-grid",
      class: "has-sub",
      badge: "",
      badgeClass: "",
      isExternalLink: false,
      isImportant: false,
      submenu: [
        {
          path: "/uikit/colorpalettes",
          title: "Colorpalettes",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/uikit/grids",
          title: "Grids",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/uikit/typography",
          title: "typography",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/uikit/textutilities",
          title: "textutilities",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/uikit/syntaxhighlighter",
          title: "syntaxhighlighter",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/uikit/helperclasses",
          title: "helperclasses",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/uikit/feather",
          title: "feather",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/uikit/font-awesome",
          title: "font-awesome",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/uikit/simple-line",
          title: "textutilities",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
      ],
    },

    {
      path: "",
      title: "Pages",
      icon: "ft-copy",
      class: "has-sub",
      badge: "",
      badgeClass: "",
      isExternalLink: false,
      isImportant: false,
      submenu: [
        {
          path: "",
          title: "Authentication",
          icon: "ft-arrow-right submenu-icon",
          class: "has-sub",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [
            {
              path: "/pages/forgotpassword",
              title: "Forgot Password",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: true,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/pages/login",
              title: "Login",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: true,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/pages/register",
              title: "Register",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: true,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/pages/lockscreen",
              title: "Lock Screen",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: true,
              isImportant: false,
              submenu: [],
            },
          ],
        },
        {
          path: "/pages/horizontaltimeline",
          title: "Horizontal Timeline",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },

        {
          path: "",
          title: "Vertical Timeline",
          icon: "ft-arrow-right submenu-icon",
          class: "has-sub",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [
            {
              path: "/pages/timeline-vertical-center",
              title: "Center",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/pages/timeline-vertical-left",
              title: "Left",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/pages/timeline-vertical-right",
              title: "Right",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
          ],
        },

        {
          path: "/pages/account-settings",
          title: "Account Settings",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/profile",
          title: "User Profile",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/invoice",
          title: "Invoice",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/error",
          title: "Error",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: true,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/comingsoon",
          title: "Coming Soon",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: true,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/maintenance",
          title: "Maintenance",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: true,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/gallery",
          title: "Gallery",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/search",
          title: "Search",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/faq",
          title: "FAQ",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/pages/kb",
          title: "Knowledge Base",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
      ],
    },
    {
      path: "https://pixinvent.com/apex-angular-4-bootstrap-admin-template/documentation",
      title: "Documentation",
      icon: "ft-book",
      class: "",
      badge: "",
      badgeClass: "",
      isExternalLink: true,
      isImportant: false,
      submenu: [],
    },
    {
      path: "https://pixinvent.ticksy.com/",
      title: "Support",
      icon: "ft-life-buoy",
      class: "",
      badge: "",
      badgeClass: "",
      isExternalLink: true,
      isImportant: false,
      submenu: [],
    },
    {
      path: "",
      title: "Forms",
      icon: "ft-edit",
      class: "has-sub",
      badge: "New",
      badgeClass: "badge badge-pill badge-primary float-right mr-1 mt-1",
      isExternalLink: false,
      isImportant: false,
      submenu: [
        {
          path: "",
          title: "Elements",
          icon: "ft-arrow-right submenu-icon",
          class: "has-sub",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [
            {
              path: "/forms/inputs",
              title: "Inputs",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/input-groups",
              title: "Input Groups",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/radio",
              title: "Radio",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/checkbox",
              title: "Checkbox",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/switch",
              title: "Switch",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/select",
              title: "Select",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/editor",
              title: "Editor",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/tags",
              title: "Input Tags",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/datepicker",
              title: "Datepicker",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
            {
              path: "/forms/timepicker",
              title: "Timepicker",
              icon: "ft-arrow-right submenu-icon",
              class: "",
              badge: "",
              badgeClass: "",
              isExternalLink: false,
              isImportant: false,
              submenu: [],
            },
          ],
        },
        {
          path: "/forms/layout",
          title: "Layouts",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/forms/validation",
          title: "Validation",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
        {
          path: "/forms/archwizard",
          title: "Wizard",
          icon: "ft-arrow-right submenu-icon",
          class: "",
          badge: "",
          badgeClass: "",
          isExternalLink: false,
          isImportant: false,
          submenu: [],
        },
      ],
    },
    // // until here
  ]);
}
//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = routeinuse;

//   //delete start here

//    //delete start here

//     //delete start here

//      //delete start here
